# Generated by Django 5.2.7 on 2025-10-22 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_migrate_stock_to_inventory'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='inventario',
            name='unique_disco_sucursal',
        ),
        migrations.RemoveConstraint(
            model_name='inventario',
            name='unique_instrumento_sucursal',
        ),
        migrations.AlterUniqueTogether(
            name='inventario',
            unique_together={('producto_disco', 'sucursal'), ('producto_instrumento', 'sucursal')},
        ),
    ]
