# Generated by Django 5.2.7 on 2025-11-03 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_perfilusuario_tipo_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriainstrumento',
            name='tipo',
            field=models.CharField(choices=[('instrumento', 'Instrumento'), ('refaccion', 'Refacción'), ('accesorio', 'Accesorio')], default='instrumento', max_length=12),
        ),
    ]
