# Generated by Django 5.2.7 on 2025-11-04 23:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_categoriainstrumento_tipo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventario',
            unique_together={('producto_instrumento', 'sucursal')},
        ),
        migrations.AddField(
            model_name='inventario',
            name='formato_disco',
            field=models.CharField(blank=True, choices=[('vinilo', 'Vinilo'), ('cd', 'CD'), ('digital', 'Digital'), ('casete', 'Casete')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='disco',
            name='año_lanzamiento',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1950, message='El año debe ser mayor o igual a 1950'), django.core.validators.MaxValueValidator(2025, message='El año no puede ser mayor a 2025')]),
        ),
        migrations.AlterUniqueTogether(
            name='inventario',
            unique_together={('producto_disco', 'formato_disco', 'sucursal'), ('producto_instrumento', 'sucursal')},
        ),
        migrations.AddConstraint(
            model_name='inventario',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('formato_disco__isnull', False), ('producto_disco__isnull', False)), ('producto_disco__isnull', True), _connector='OR'), name='formato_solo_para_discos'),
        ),
    ]
