# Generated by Django 5.2.8 on 2025-11-11 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_refacciones_taxonomia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refaccion',
            name='modelo_compatible',
            field=models.CharField(blank=True, help_text='Modelo(s) específico(s) con los que es compatible (texto libre)', max_length=200),
        ),
        migrations.CreateModel(
            name='ConversacionWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_whatsapp', models.CharField(help_text='Número de WhatsApp del cliente', max_length=20)),
                ('nombre_cliente', models.CharField(blank=True, help_text='Nombre del cliente si está disponible', max_length=200)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('resuelta', 'Resuelta'), ('en_espera', 'En Espera')], default='activa', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_ultimo_mensaje', models.DateTimeField(auto_now=True)),
                ('contexto', models.TextField(blank=True, help_text='Contexto de la conversación para el bot')),
            ],
            options={
                'verbose_name': 'Conversación WhatsApp',
                'verbose_name_plural': 'Conversaciones WhatsApp',
                'ordering': ['-fecha_ultimo_mensaje'],
                'indexes': [models.Index(fields=['numero_whatsapp'], name='tasks_conve_numero__c6ca50_idx'), models.Index(fields=['estado'], name='tasks_conve_estado_0ef3f8_idx')],
            },
        ),
        migrations.CreateModel(
            name='MensajeWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrante', 'Entrante'), ('saliente', 'Saliente')], max_length=10)),
                ('contenido', models.TextField()),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('es_bot', models.BooleanField(default=False, help_text='Indica si el mensaje fue generado por el bot')),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='tasks.conversacionwhatsapp')),
            ],
            options={
                'verbose_name': 'Mensaje WhatsApp',
                'verbose_name_plural': 'Mensajes WhatsApp',
                'ordering': ['fecha_envio'],
            },
        ),
    ]
